### ISSUE TITLE
how to setup with react native 0.73.4?

### ISSUE THREAD

**Issue by PhamMinhKha** [pedrol2b/voice#3]
Result return undefined

**Comment by pedrol2b** [comment]
👋🏻 Sorry for the late reply, it should all be working fine in the latest release [v3.2.8](https://github.com/pedrol2b/react-native-voice/releases/tag/v3.2.8)

https://github.com/pedrol2b/react-native-voice/assets/107975184/4260886d-1c40-4ea2-a90a-1ab197ce6506

But for futher investigation, be sure to include more information!
feel free to reach me on discord @pedrol2b

> [!NOTE]  
> The documentation is not yet updated, i'll be updating it soon as well as creating an `example` repo, for now you can check a minimal reproduction at [example-react-native-voice](https://github.com/pedrol2b/example-react-native-voice), just change the old voice package with this one all should all be working fine!

**Comment by PhamMinhKha** [comment]
"Sorry. This is my fault, my phone isn't working but another phone is."
